/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#0b1c30",
        "surface-dim": "#CBD5E1",
        "surface-container-lowest": "#FFFFFF",
        "on-tertiary-container": "#c5d6f0",
        "inverse-on-surface": "#F8FAFC",
        "inverse-primary": "#b7c4ff",
        "on-surface": "#0F172A",
        "error-container": "#ffdad6",
        "surface-bright": "#FFFFFF",
        "surface": "#FFFFFF",
        "on-tertiary-fixed-variant": "#38485d",
        "on-background": "#0F172A",
        "tertiary-fixed-dim": "#b7c8e1",
        "on-secondary": "#FFFFFF",
        "on-secondary-fixed": "#131b2e",
        "tertiary-fixed": "#d3e4fe",
        "surface-container-highest": "#E2E8F0",
        "inverse-surface": "#0B1628",
        "primary-fixed": "#dce1ff",
        "primary-container": "#1D4ED8",
        "secondary-container": "#E2E8F0",
        "on-secondary-container": "#64748B",
        "on-error": "#FFFFFF",
        "surface-container-low": "#F6F8FB",
        "outline-variant": "#E2E8F0",
        "on-tertiary": "#FFFFFF",
        "on-primary-container": "#cad3ff",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary": "#36455b",
        "surface-variant": "#E2E8F0",
        "secondary": "#64748B",
        "on-error-container": "#93000a",
        "tertiary-container": "#4d5d73",
        "background": "#F8FAFC",
        "on-surface-variant": "#64748B",
        "surface-container-high": "#F1F5F9",
        "surface-tint": "#1D4ED8",
        "primary-fixed-dim": "#b7c4ff",
        "primary": "#1D4ED8",
        "secondary-fixed": "#dae2fd",
        "error": "#EF4444",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#001551",
        "on-primary-fixed-variant": "#0039b5",
        "on-primary": "#FFFFFF",
        "outline": "#94A3B8",
        "surface-container": "#F6F8FB"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "32px",
        "container-max": "1440px",
        "margin-mobile": "16px",
        "unit": "8px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-lg": ["Inter"],
        "label-md": ["Inter"],
        "label-sm": ["Inter"],
        "headline-sm": ["Inter"],
        "label-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}

